import { pgEnum } from "drizzle-orm/pg-core";
import { z } from "zod";

export const SURVEY_STATUS = ["DRAFT", "ACTIVE", "PAUSED", "ARCHIVED"] as const;
export const SURVEY_STATUS_SCHEMA = pgEnum("survey_status", SURVEY_STATUS);
const SurveyStatusZodType = z.enum(SURVEY_STATUS);
export type SurveyStatusType = z.infer<typeof SurveyStatusZodType>;

export const USER_PRIVILEGE = ["ORIGINATOR", "RESPONDENT"] as const;
export const USER_PRIVILEGE_SCHEMA = pgEnum("user_privilege", USER_PRIVILEGE);
const UserPrivilegeZodType = z.enum(USER_PRIVILEGE);
export type UserPrivilegeType = z.infer<typeof UserPrivilegeZodType>;

export const METADATA_TYPES = [
  "NUMBER",
  "RANGE",
  "TEXT",
  "URL",
  "EMAIL",
] as const;
export const METADATA_TYPES_SCHEMA = pgEnum(
  "survey_metadata_types",
  METADATA_TYPES,
);
const MetadataTypesZodType = z.enum(METADATA_TYPES);
export type MetadataType = z.infer<typeof MetadataTypesZodType>;

export const ORGANISATION_SIZE_TYPES = [
  "1-49",
  "50-249",
  "250-1000",
  "1000+",
] as const;

export const ORGANISATION_SIZE_TYPES_SCHEMA = pgEnum(
  "organisation_size_types",
  ORGANISATION_SIZE_TYPES,
);

const OrganizationSizeTypesZodType = z.enum(ORGANISATION_SIZE_TYPES);
export type OrganizationSizeType = z.infer<typeof OrganizationSizeTypesZodType>;

export const COUNTRY_TYPES = [
Afghanistan,
Bangladesh,
Bhutan,
India,
Iran, Isl. Rep.,
Kazakhstan,
Kyrgyzstan,
Maldives,
Nepal,
Pakistan,
Sri Lanka,
Tajikistan,
Turkmenistan,
Uzbekistan,
Brunei Daruss.,
Cambodia,
China,
DPR Korea,
Hong Kong, China,
Indonesia,
Japan,
Lao PDR,
Macao, China,
Malaysia,
Mongolia,
Myanmar,
Philippines,
Rep. of Korea,
Singapore,
Thailand,
Timor-Leste,
Viet Nam,
Albania,
Andorra,
Austria,
Belarus,
Belgium,
Bermuda,
Bosnia/Herzeg.,
Bulgaria,
Canada,
Croatia,
Czechia,
Denmark,
Estonia,
Finland,
France,
Germany,
Greece,
Hungary,
Iceland,
Ireland,
Italy,
Latvia,
Liechtenstein,
Lithuania,
Luxembourg,
Malta,
Monaco,
Montenegro,
Netherlands,
North Macedonia,
Norway,
Poland,
Portugal,
Rep. Moldova,
Romania,
Russian Fed.,
San Marino,
Serbia,
Slovakia,
Slovenia,
Spain,
Sweden,
Switzerland,
Ukraine,
United Kingdom,
United States,
Anguilla,
Antigua/Barbuda,
Argentina,
Aruba,
Bahamas,
Barbados,
Belize,
Bolivia,
Brazil,
Br. Virgin Is,
Cayman Is,
Chile,
Colombia,
Costa Rica,
Cuba,
Curaçao,
Dominica,
Dominican Rep.,
Ecuador,
El Salvador,
Grenada,
Guatemala,
Guyana,
Haiti,
Honduras,
Jamaica,
Mexico,
Montserrat,
Nicaragua,
Panama,
Paraguay,
Peru,
St Kitts/Nevis,
Saint Lucia,
St Vincent/Grenad.,
Sint Maarten,
Suriname,
Trinidad/Tobago,
Turks/Caicos Is,
Uruguay,
Venezuela, B. R.,
Algeria,
Armenia,
Azerbaijan,
Bahrain,
Cyprus,
Egypt,
Georgia,
Iraq,
Israel,
Jordan,
Kuwait,
Lebanon,
Libya,
Morocco,
Oman,
Palestine,
Qatar,
Saudi Arabia,
Sudan,
Syrian A. R.,
Tunisia,
Turkey,
U. A. Emirates,
Yemen,
Australia,
Cook Islands,
Fiji,
Kiribati,
Marshall Is,
Micronesia, F. S.,
Nauru,
New Zealand,
Niue,
Palau,
Papua N. Guinea,
Samoa,
Solomon Is,
Tokelau,
Tonga,
Tuvalu,
Vanuatu,
Angola,
Benin,
Botswana,
Burkina Faso,
Burundi,
Cabo Verde,
Cameroon,
C. A. R.,
Chad,
Comoros,
Congo,
Côte d'Ivoire,
D. R. Congo,
Djibouti,
Equat. Guinea,
Eritrea,
Eswatini,
Ethiopia,
Gabon,
Gambia,
Ghana,
Guinea,
Guinea-Bissau,
Kenya,
Lesotho,
Liberia,
Madagascar,
Malawi,
Mali,
Mauritania,
Mauritius,
Mozambique,
Namibia,
Niger,
Nigeria,
Rwanda,
S. Tome/Principe,
Senegal,
Seychelles,
Sierra Leone,
Somalia,
South Africa,
South Sudan,
Togo,
Uganda,
U. R. Tanzania,
Zambia,
Zimbabwe
] as const;

export const COUNTRY_TYPES_SCHEMA = pgEnum("countries", COUNTRY_TYPES);

const CountryTypesZodType = z.enum(COUNTRY_TYPES);
export type CountryTypes = z.infer<typeof CountryTypesZodType>;

export const INDUSTRY_TYPES = [
  "Accounting",
  "Airlines / Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel / Fashion",
  "Architecture / Planning",
  "Arts / Crafts",
  "Automotive",
  "Aviation / Aerospace",
  "Banking / Mortgage",
  "Biotechnology / Greentech",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies / Equipment",
  "Capital Markets / Hedge Fund / Private Equity",
  "Chemicals",
  "Civic / Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software / Engineering",
  "Computer / Network Security",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense / Space",
  "Design",
  "E - Learning",
  "Education Management",
  "Electrical / Electronic Manufacturing",
  "Entertainment / Movie Production",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food Production",
  "Food / Beverages",
  "Fundraising",
  "Furniture",
  "Gambling / Casinos",
  "Glass / Ceramics / Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design / Web Design",
  "Health / Fitness",
  "Higher Education / Acadamia",
  "Hospital / Health Care",
  "Hospitality",
  "Human Resources / HR",
  "Import / Export",
  "Individual / Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology / IT",
  "Insurance",
  "International Affairs",
  "International Trade / Development",
  "Internet",
  "Investment Banking / Venture",
  "Investment Management / Hedge Fund / Private Equity",
  "Judiciary",
  "Law Enforcement",
  "Law Practice / Law Firms",
  "Legal Services",
  "Legislative Office",
  "Leisure / Travel",
  "Library",
  "Logistics / Procurement",
  "Luxury Goods / Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Market Research",
  "Marketing / Advertising / Sales",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Equipment",
  "Medical Practice",
  "Mental Health Care",
  "Military Industry",
  "Mining / Metals",
  "Motion Pictures / Film",
  "Museums / Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers / Journalism",
  "Non - Profit / Volunteering",
  "Oil / Energy / Solar / Greentech",
  "Online Publishing",
  "Other Industry",
  "Outsourcing / Offshoring",
  "Package / Freight Delivery",
  "Packaging / Containers",
  "Paper / Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary / Secondary Education",
  "Printing",
  "Professional Training",
  "Program Development",
  "Public Relations / PR",
  "Public Safety",
  "Publishing Industry",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate / Mortgage",
  "Recreational Facilities / Services",
  "Religious Institutions",
  "Renewables / Environment",
  "Research Industry",
  "Restaurants",
  "Retail Industry",
  "Security / Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing / Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation / Localization",
  "Transportation",
  "Utilities",
  "Venture Capital / VC",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine / Spirits",
  "Wireless",
  "Writing / Editing",
] as const;

export const INDUSTRY_TYPES_SCHEMA = pgEnum("industries", INDUSTRY_TYPES);

const IndustryTypesZodType = z.enum(INDUSTRY_TYPES);
export type IndustryTypes = z.infer<typeof IndustryTypesZodType>;

export const ROLE_TYPES = ["ADMIN", "USER"] as const;

export const ROLE_TYPES_SCHEMA = pgEnum("roles", ROLE_TYPES);

const RoleTypesZodType = z.enum(ROLE_TYPES);
export type RoleTypes = z.infer<typeof RoleTypesZodType>;
